### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by jfirebaugh** [termi/DOM-Keyboard-Event-Level-3-polyfill#1]
Throws an error at [DOMEventsLevel3.shim.js:958](https://github.com/termi/DOM-Keyboard-Event-Level-3-polyfill/blob/3088b90fbee9421db442b859b33fe372f3f9cc4d/DOMEventsLevel3.shim.js#L958):

```
TypeError: Attempting to change writable attribute of unconfigurable property.
```

**Comment by termi** [comment]
Thx. I am now working on version 2 of this polyfill. It's coming soon.

**Comment by termi** [comment]
fixed
