### ISSUE TITLE
No keydown events are sent when Cmd is active on mac

### ISSUE THREAD

**Issue by ibdknox** [termi/DOM-Keyboard-Event-Level-3-polyfill#2]
for example, cmd+k won't ever show the k in your demo 1 page

EDIT: this is in Chrome 26

**Comment by ibdknox** [comment]
Same in Canary

**Comment by termi** [comment]
Thanks for the report. Please [try it now](http://h123.ru/-/tests/KeyboardEvent/). If bug still here I will reopen this issue.

Also I add important note in readme, you should read it.
